"use client";

import { useState } from "react";
import type { User } from "@supabase/supabase-js";
import { forecast, periodBounds, streaks, summarize, type Period } from "@/lib/analytics";
import { dateKey, formatDate, fromDateKey, shiftDays } from "@/lib/date";
import type { Entry } from "@/lib/entries";
import { TargetsPanel } from "./targets-panel";

export function AnalyticsDashboard({ entries, today, user, onChooseDate, loading }: { entries: Entry[]; today: string; user: User; onChooseDate: (key: string) => void; loading: boolean }) {
  const [period, setPeriod] = useState<Period>("week");
  const [anchor, setAnchor] = useState(today);
  const summary = summarize(entries, today, anchor || today, period);
  const streak = streaks(entries, today);
  const allTime = forecast(entries, today, 0).allTime;
  const maximum = Math.max(1, ...summary.points.map(p => p.value));
  const counts = new Map(entries.map(e => [e.date, e.count]));
  const heatDays = Array.from({ length: 84 }, (_, i) => dateKey(shiftDays(fromDateKey(today), i - 83)));
  const heatMax = Math.max(1, ...heatDays.map(key => counts.get(key) ?? 0));
  const best = entries.filter(e => e.date >= summary.start && e.date <= summary.end && e.date <= today).sort((a, b) => b.count - a.count)[0];
  const isCurrent = periodBounds(today, period).start === summary.start;

  function navigate(direction: number) {
    const next = direction < 0 ? dateKey(shiftDays(fromDateKey(summary.start), -1)) : dateKey(shiftDays(fromDateKey(summary.end), 1));
    if (next <= today && next >= "0001-01-01") setAnchor(next);
  }
  return <div className="dashboard">
    <div className="page-heading"><div><span className="eyebrow">PRACTICE & PROGRESS <span className="eyebrow-line"/></span><h1>Your dashboard<span className="accent">.</span></h1><p>A clearer view of your rhythm and where it can take you.</p></div><div className="all-time"><strong>{allTime.toLocaleString()}</strong><span>ALL-TIME JAAP</span></div></div>
    {loading && <p role="status">Syncing your latest tallies…</p>}
    <div className="dashboard-toolbar"><div className="period-tabs" role="group" aria-label="Analytics period">{(["week", "month", "year"] as Period[]).map(value => <button key={value} className={period === value ? "active" : ""} aria-pressed={period === value} onClick={() => { setPeriod(value); setAnchor(today); }}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div><div className="period-navigation"><button aria-label={`Previous ${period}`} disabled={summary.start <= "0001-01-01"} onClick={() => navigate(-1)}>‹</button><span>{period === "week" ? `${formatDate(summary.start, { month: "short", day: "numeric", year: "numeric" })} – ${formatDate(summary.end, { month: "short", day: "numeric" })}` : formatDate(summary.start, period === "month" ? { month: "long", year: "numeric" } : { year: "numeric" })}</span><button aria-label={`Next ${period}`} disabled={isCurrent} onClick={() => navigate(1)}>›</button>{!isCurrent && <button className="period-now" onClick={() => setAnchor(today)}>Today</button>}</div></div>
    <div className="dashboard-stats"><article className="stat-card stat-total"><span>TOTAL JAAP</span><strong>{summary.total.toLocaleString()}</strong><p>{summary.change === null ? summary.total > 0 ? "A new beginning this period" : "Start with one saved tally" : `${summary.change >= 0 ? "↑" : "↓"} ${Math.abs(summary.change).toFixed(1)}% vs previous ${period}`}</p><small>{isCurrent ? "Compared through the same elapsed day" : "Compared with the full previous period"}</small></article><article className="stat-card"><span>DAILY AVERAGE</span><strong>{Math.round(summary.average).toLocaleString()}</strong><p>Across {summary.days} calendar days</p><small>Includes days with no tally</small></article><article className="stat-card"><span>CONSISTENCY</span><strong>{Math.round(summary.consistency)}<em>%</em></strong><p>{summary.active} active / {summary.days} days</p><small>Days with a positive tally</small></article><article className="stat-card"><span>CURRENT STREAK</span><strong>{streak.current}<em>days</em></strong><p>Best streak: {streak.longest} days</p><small>Today can still keep it going</small></article></div>
    <div className="dashboard-chart-grid"><section className="dashboard-card rhythm-card"><div className="section-heading"><div><h2>{period === "year" ? "Monthly" : "Daily"} rhythm</h2><p>{period === "year" ? "Choose a month to explore its days" : "Choose a bar to edit that day's tally"}</p></div><span className="chart-unit">JAAP</span></div><div className={`rhythm-chart ${period === "month" ? "dense" : ""}`}>{summary.points.map(point => <button key={point.date} className={`rhythm-column${point.date === today ? " current" : ""}`} disabled={point.future} aria-label={`${formatDate(point.date, period === "year" ? { month: "long", year: "numeric" } : { day: "numeric", month: "long", year: "numeric" })}: ${point.value.toLocaleString()} jaap${point.future ? ", future" : ""}`} title={`${point.date}: ${point.value.toLocaleString()}`} onClick={() => { if (period === "year") { setPeriod("month"); setAnchor(point.date); } else onChooseDate(point.date); }}><span className="rhythm-value">{period !== "month" && point.value > 0 ? point.value.toLocaleString() : ""}</span><span className="rhythm-track"><i style={{ height: `${point.value ? Math.max(4, point.value / maximum * 100) : 2}%` }}/></span><span className="rhythm-label">{point.label}</span></button>)}</div><div className="rhythm-footer"><span>● Saved jaap</span><span>{summary.total === 0 ? "Your next tally will appear here" : `${summary.total.toLocaleString()} jaap this ${period}`}</span></div></section><section className="dashboard-card highlights-card"><span className="card-kicker">A LITTLE PERSPECTIVE</span><h2>Your practice highlights</h2><div><small>Strongest day this {period}</small><strong>{best?.count ? best.count.toLocaleString() : "—"}<span>{best?.count ? " jaap" : ""}</span></strong><p>{best?.count ? formatDate(best.date, { weekday: "long", month: "short", day: "numeric" }) : "Save a tally to find your strongest day"}</p></div><div><small>Recent daily pace</small><strong>{Math.round(forecast(entries, today, 0).pace).toLocaleString()}<span> jaap/day</span></strong><p>Up to 28 completed calendar days</p></div><p className="highlight-note">Consistency grows one day at a time. A small tally still counts.</p></section></div>
    <section className="dashboard-card heatmap-card"><div className="section-heading"><div><h2>84 days of practice</h2><p>Each square is a day. Choose one to view or edit it.</p></div><span className="heatmap-range">{formatDate(heatDays[0], { month: "short", day: "numeric" })} – today</span></div><div className="heatmap-scroll"><div className="heatmap-grid">{heatDays.map(key => { const value = counts.get(key) ?? 0; const level = value ? Math.max(1, Math.ceil(value / heatMax * 4)) : 0; return <button key={key} className={`heat-cell level-${level}`} title={`${key}: ${value.toLocaleString()} jaap`} aria-label={`${formatDate(key, { month: "long", day: "numeric", year: "numeric" })}: ${value.toLocaleString()} jaap`} onClick={() => onChooseDate(key)}/>; })}</div></div><div className="heatmap-footer"><span>{heatDays.filter(key => (counts.get(key) ?? 0) > 0).length} active days in the last 84 days</span><span className="heatmap-legend">Less {[0, 1, 2, 3, 4].map(level => <i key={level} className={`level-${level}`}/>)} More</span></div></section>
    <TargetsPanel entries={entries} today={today} user={user}/>
  </div>;
}
